---
sumo_tarball_url: https://sourceforge.net/projects/sumo/files/sumo/version%201.4.0/sumo-src-1.4.0.tar.gz/download
sumo_tarball_filename: sumo-src-1.4.0.tar.gz
sumo_tarball_sha1: 9376726b592b5c13b9cad63d80d43c67adeadafe
sumo_dir: sumo-1.4.0
